---
# tasks file for hoplacloud.postfix

- name: Install latest version of postfix
  apt:
    name: postfix
    state: latest

- name: Install python3-dnspython
  apt:
    name: python3-dnspython
    state: latest

- name: Install dnsutils
  apt:
    name: dnsutils
    state: latest
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

- name: Get public_ipv4
  command: dig TXT +short o-o.myaddr.l.google.com @ns1.google.com -4
  register: public_ipv4

- name: This is the target public IP
  debug:
     msg: "Public IP v4 is : {{ public_ipv4.stdout | regex_replace('\"', '')}}"

- name: Get PTR v4
  command: dig +short -x "{{ public_ipv4.stdout | regex_replace('\"', '') }}"
  register: ptr_ipv4

- name: This is the target reverse DNS
  debug:
     msg: "Reverse DNS is {{ ptr_ipv4.stdout | regex_replace('.$', '') }}"

- set_fact:
    public_ipv4: "{{ public_ipv4.stdout | regex_replace('\"', '') }}"
    ptr_v4: "{{ ptr_ipv4.stdout | regex_replace('.$', '') }}"

- name: Setup smtpd_banner in postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtpd_banner'
    line: 'smtpd_banner = $myhostname ESMTP'

- name: Setup aliases
  lineinfile:
    path: /etc/aliases
    insertafter: "^postmaster"
    line: "{{ user_name }}: {{ user_email }}"
  register: new_alias

- name: rum newaliases command
  command: newaliases
  when: new_alias is changed

- name: Setup myhostname in postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^myhostname'
#    line: "myhostname = {{ lookup('dig', ipify_public_ip | join, 'qtype=PTR')[:-1] }}"
    line: "myhostname = {{ ptr_v4 }}"

- name: Setup inet_protocols to IPV4
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_protocols'
    line: "inet_protocols = ipv4"

- name: Add a line smtputf8_enable to main.cf
  lineinfile:
    path: /etc/postfix/main.cf
    line: "smtputf8_enable = no"
    create: yes

- name: Restart postfix
  service: name=postfix state=restarted
